### ISSUE TITLE
Investigate why Sam has read only access 

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#10]
Sam has not been able to complete issue #9, since he appears to only have read access to the "MECH ENG Complete Rubric."  Bogdan, can you please look into this.  It may be a where we don't understand the proper process.

**Comment by bhancas** [comment]
Should be fixed now. The issue was that when we went through the demo a week ago I checked out his template and didn't check it back in so he only had read only access. Just so you know moving forward, as a manager you can go to the Workflow Dashboard and force a template to be checked back in if needed. Please try again and let me know if you still have issues.
