### ISSUE TITLE
Test Course Report Template on Mac

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#128]
Please set up the "new" mac and test.

**Comment by arana2** [comment]
Testing Criteria:
1.  Opening the Course Report Mac Template
2. Viewing Contents of the Template
3. Reviewing if the Vena add-in works
4. Updating the Contents of the Template

Detailed Testing Criteria:
1.  Open Course Report Mac Template [**Pass**]
a. Accessing the template: Manager -> files Library -> Reports -> Course Report MAC.xlsm
b. Selecting the Program, Year, and Section [**Pass**]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/38359810/39430888-19a0d17c-4c5d-11e8-96c2-834340257dd7.png">


2.  Viewing contents of the template
  a. Detail Chart [**Pass**]
<img width="734" alt="screen shot 2018-04-30 at 10 02 53 am" src="https://user-images.githubusercontent.com/38359810/39431122-bb9f98dc-4c5d-11e8-8e1e-46b3a2ed868d.png">

  b. Summary Chart [**Pass**]
<img width="1000" alt="screen shot 2018-04-30 at 10 04 06 am" src="https://user-images.githubusercontent.com/38359810/39431153-db4461f4-4c5d-11e8-9a52-fc2eefa301e5.png">

3.  Checking if the Vena Add-in loads automatically [**Fail**]
      - To access the Vena Add-in, go to Insert -> Click Vena Add-in
      - The Vena Add-in does not initially load when opening the template
**Error code 1001 appears**
In order to reconnect, press the [i] button and select reload
User will need to enter Vena Credentials
<img width="450" alt="image" src="https://user-images.githubusercontent.com/38359810/39431303-4f13ad2e-4c5e-11e8-91b2-440920e7c3d1.png">
<img width="129" alt="image" src="https://user-images.githubusercontent.com/38359810/39431353-766ca628-4c5e-11e8-93c0-f875eeabaf05.png">

4.  Updating the Course Report Template
The Line Item Details section is disabled.  Therefore, cannot make any updates to the contents of the course report template.
  a. Insert data [**Fail**]
  b. Remove data [**Fail**]
  c. Move data [**Fail**]
<img width="196" alt="screen shot 2018-04-30 at 10 14 35 am" src="https://user-images.githubusercontent.com/38359810/39431638-55bec568-4c5f-11e8-810c-2f97a8ea5dbc.png">


  d. Update existing data [Pass], Saving the data [**Fail**]
<img width="126" alt="image" src="https://user-images.githubusercontent.com/38359810/39431606-40aacb54-4c5f-11e8-82f0-5d1820941e98.png">

**Comment by arana2** [comment]
Closing this ticket as the Course Report for the Mac is working as expected.
