### ISSUE TITLE
Historical Program Measurement Report

### ISSUE THREAD

**Issue by arana2** [smiths/MEASURE#131]
Execute the Historical Program Measurement Report

**Comment by arana2** [comment]
@smiths I successfully executed the Historical Program Measurement Report.  It is displaying the report for 2016-2017, but no data prior to that.  I'm assuming we didn't enter data prior to the 2016-2017 term?

Steps:

1.  Open Historical Program Measurement Report
![image](https://user-images.githubusercontent.com/38359810/39487521-7e25b266-4d4d-11e8-982e-b63635da8ca2.png)

2.  Enable Macros

3.  Choose Attribute and Scenario
![image](https://user-images.githubusercontent.com/38359810/39487531-87774c9e-4d4d-11e8-8385-7486be581e6e.png)

4.  Output
![image](https://user-images.githubusercontent.com/38359810/39487538-8e8491c2-4d4d-11e8-834b-95b2515a3876.png)

**Comment by smiths** [comment]
@arana2 great to see the report generated.   Your results make sense.  I do not think that any data was entered for software engineering for any year other than 2016-2017.  There was some data entered for a few programs though.  Can you have a quick look at the historical measures reports for chemical engineering and mechanical engineering?  It isn't anything to worry about if they don't have data, since my memory may be faulty, but if there is some data it would be nice to see a non-flat graph.  😄

**Comment by arana2** [comment]
@smiths  - you're correct :)  

I was able to pull the reports for Chemical Engineering and Mechanical Engineering for both the 2014/15 Year and 2016/2017 Year.

**Chemical Engineering**
![image](https://user-images.githubusercontent.com/38359810/39491432-64f8efd0-4d5a-11e8-9f99-2e1b5e9d0bad.png)

**Mechanical Engineering**
![image](https://user-images.githubusercontent.com/38359810/39491502-a3e1a7a0-4d5a-11e8-9221-1ff8e289c381.png)

**Comment by smiths** [comment]
Nice to see that we have this data.  When this year's data is added, we'll have one more data point.  😄
