### ISSUE TITLE
Test for Vena Add-In

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#149]
I don't know how feasible this is, but I have heard feedback from users that they would like Vena to check for the presence of the Excel Add-In when a new spreadsheet is loaded on their local machine.  In some cases people forget that the Add-In is needed, especially when they move to a new computer and reinstall Excel.

**Comment by arana2** [comment]
This might be for Accreditation 3.0.  However, I'll take a look and see what we can do as a temporary solution.

**Comment by arana2** [comment]
I created a VBA script to detect if the Vena Addin has been installed for Windows.  Still working on the script for Mac users as well.

**Comment by smiths** [comment]
Great that you were able to create a VBA script!  Good luck with the Mac script.

**Comment by arana2** [comment]
- As discussed with the Vena Team, the Vena templates have a built-in feature that checks if the Mac User has the Vena add-in installed when a Vena template is opened
- When a Vena template is downloaded and opened where the Mac User does not have the Vena add-in installed, the Office store will suggest installing the Vena Add-in
![image](https://user-images.githubusercontent.com/38359810/43979070-7d3e948a-9cb7-11e8-8ecc-76ba6cb2e670.png)
- If the user clicks “Trust this add-in”, Vena Contributor Connector will be installed into Microsoft Office 

Note: This feature currently does not exist in the Windows environment.  We could implement my code in our templates/reports to detect if the Vena add-in has been installed for Windows users and let Vena's built-in feature to detect if Vena has been installed for our Mac users

Thoughts?

**Comment by smiths** [comment]
This sounds good to me @arana2.  I cannot see a downside to your proposal.

**Comment by arana2** [comment]
We have successfully implemented the feature and tested all of our production Vena templates and Vena reports.

![image](https://user-images.githubusercontent.com/38359810/44224323-11a4b100-a158-11e8-8016-81ea081fa4a4.png)

**Windows Users**
In order to execute the code, the user must continue to enable editing and enable macros
![image](https://user-images.githubusercontent.com/38359810/44224365-300aac80-a158-11e8-973d-9dbf852c6e40.png)
![image](https://user-images.githubusercontent.com/38359810/44224374-3436ca00-a158-11e8-8ebe-0488d8b6eaad.png)
 
If Vena is not installed, display message:
![image](https://user-images.githubusercontent.com/38359810/44224400-4284e600-a158-11e8-9fa4-0496aa528dd7.png)
 
**Mac Users**
If Vena is not installed, the Microsoft store will suggest the user to download the Vena Add-in
The user must press “Trust this add-in” to install Vena Add-in:
![image](https://user-images.githubusercontent.com/38359810/44224425-53355c00-a158-11e8-8763-e3f1cd4e8796.png)
 
**Other OS**
If the user opens a template/report with another operating system and is incompatible with Vena, the code will notify the user that Vena is incompatible and have them contact their accreditation administrator
Sample Message:
![image](https://user-images.githubusercontent.com/38359810/44224622-00a86f80-a159-11e8-8c2a-c1e942f73e62.png)

**Comment by arana2** [comment]
Hi @smiths ,

Not sure if you had a chance to review this feature, but it has been implemented in all of the templates/reports listed in my previous comment.

If you are aligned, may we close this ticket?

Thanks,
Andrew

**Comment by smiths** [comment]
Great work @arana2.  Yes, we can close this issue.
