### ISSUE TITLE
Chronological Order for the List of Years under "Select a member:"

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#36]
When selecting the specific data to fill a rubric (or other template), the years under "Select a member:" are listed in what appears to be the order of creation.  Would it be possible to list the years in chronological order?  That is, in the order 2013-2014, 2014-2015, 2015-2016, etc.  Going forward the years will be added in chronological order, but right now with the addition of 2013-2014, we have broken this ordering.

My thinking is that it will make it easier for the users if the options are listed in a logical order.

**Comment by EvanVena** [comment]
@smiths @bhancas 
This is suggested to be done at the data model level. Because the data model controls all the input template and reports.
I did it for the year, please see the attached pictures

![image](https://cloud.githubusercontent.com/assets/20912011/18251548/aab9e986-7357-11e6-96e8-21d610f3429e.png)
![image](https://cloud.githubusercontent.com/assets/20912011/18251589/dea836b2-7357-11e6-9212-8e2bd3dd1181.png)

**Comment by smiths** [comment]
That makes sense Evan.  We can modify this at the Modeller level should the need arise.  Fortunately, new years going forward will likely be added in order.  I'll close this issue.
