### ISSUE TITLE
No Indicator/Learning Outcome listed in Chem Eng 2I03 Rubric (2013-2014, Term 2)

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#37]
In the rubric from CHEM ENG 2I03, 2013-2014, Term 2, the Indicator/Learning Outcome column does not have any useful information.  I believe this is partly due to @SamGrimshaw not entering a line item detail description, but shouldn't the "umbrella" indicator always be listed?  In this case Sam probably did not enter the line item detail description because there is no decomposition of the indicator into learning outcomes.  From looking at the spreadsheet, I have no idea what indicator is being assessed, even though the course report seems to have this information.

**Comment by EvanVena** [comment]
Hi @smiths @bhancas 
the line item detail will not automatically show up.
since it is indicated in the "Curriculum Mapping Input Template", 6.2 and 7.3 will be measured, but we haven't enter any detail yet, that's why it is showing up as empty row.
![image](https://cloud.githubusercontent.com/assets/20912011/18251775/225d209c-7359-11e6-9de8-9d984c0a69d9.png)

**Comment by smiths** [comment]
Thank you Evan.  This looks fine.  I thought when I looked at it the grey rows did not appear, but when I look now, they are there.  I must have been mistaken.  I'll close this issue.
