### ISSUE TITLE
Why no data for Indicators 6.2 and 7.3 for Chem Eng 2I03, 2015/16, Term 2?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#42]
Hi Sam.  I noticed that the measurement map for 2015/16 says that there should be indicators 6.2 and 7.3 for Chem Eng 2I03, but you have not included any data in the rubric.  Is this because of a problem with Vena, or is it because indicators 6.2 and 7.3 should be removed from the measurement map?

**Comment by SamGrimshaw** [comment]
The measured indicators for the 2015/16 cycle were not kept the same as the previous 2014/15 cycle. When a row was left blank, in ChE 2I03 or other courses, there was simply no data to input because the professor(s) chose not to assess it this year. At the time, when I filled out the measurement mapping by selecting what was measured with 'M' for the 2015/16 cycle, the course rubric did not update to reflect what was filled out for the mapping rubric and instead opted to repeat the same indicators used from previous years regardless.

**Comment by smiths** [comment]
Hello Sam.  This does sound like a problem.  We will need enough information that @EvanVena can reproduce this behaviour.  Can you tell me the specific indicators that you want for ChE 2I03 for 2014/2015 and for 2015/2016?

**Comment by SamGrimshaw** [comment]
According to the archived reports, ChE 2I03 measured indicators 3.3 and 5.1 for 2014/15 and 3.3, 5.1, and 7.3 for 2015/16. Indicator 6.2 was originally supposed to be measured, but no data were ever provided. In that respect, the 'Measured Indicators Input Template' for Chemical Engineering (B.Eng) for 2014/15 and 2015/16 are both correct when I check out that particular file and look for ChE 2I03.

**Comment by smiths** [comment]
Hello Sam.  I haven't been able to reproduce the problem you are describing.  When I look at the "rubric" and "course report" for ChE 2I03 for 2014-2015 and 2015-2016 everything look okay to me.  Maybe I am missing something?  I tried adding a new indicator to another course through the measurement map and the rubic and course report were updated correctly.  I deleted the additional indicator and the associated reports were updated correctly.

Maybe you could send me a screen shot and highlight the errors?  Maybe we are seeing something different when we view the templates?

**Comment by smiths** [comment]
Given that so much time has passed.  This issue will be closed.
