### ISSUE TITLE
Testing of Departmental Functions by Nicole Macdonald

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#47]
From Maria White:

"Eng Phys is happy to help us with this.  Nicole Macdonald undergraduate administrative assistant will work us (macdonne@mcmaster.ca).

Michelle will follow up with you when she has completed her part of the testing. Michelle will take the lead in contacting Nicole and starting the process when we are ready to go."

**Comment by smiths** [comment]
Michelle, please proceed with testing with Nicole.  Please set her up to do the following for Eng Phys:
- update the programs to the 2016-2017 version
- update the curriculum map
- update the measurement map
I'm assuming that you will have completed issue #74 before starting this issue with Nicole.  I would like to do the testing with Nicole before the training session with the departmental reps in the first week of November.  This is a good trial run for learning what material will be needed for the training session.

**Comment by zhengm2** [comment]
Hi Spencer,

I am meeting Nicole today to discuss this. Since the information is carried forward from the previous entry it's really just checking on her part.

**Comment by smiths** [comment]
Hello Michelle.  I would be very surprised if there are no curriculum changes since when the data was initially added to the system.  The curriculum map and measurement map have also likely changed.  If at all possible, I would like Nicole to try to add a course, change the curriculum map and change the measurement map.  I think we really need to learn if these tasks are difficult for regular departmental reps.  It is also a good test for the documentation, as you have found in issue #24 .

**Comment by zhengm2** [comment]
This is the feedback from Nicole that I previously emailed to you. I figure that I would include it here so that we have all of the information in one place should we need to access it.

-	Courses are in random order in the Curriculum Map, it’s hard to find courses and enter data quickly
-	She deleted the entries for courses that were not in their curriculum (E.g. Mech Eng courses)  We will need to add a note to not touch courses that are shared
-	IDA is confusing as some of the reports list this as Introductory, Intermediate, Advanced
-	She was unsure which table to use in the report
-	She feels like she’s entering data twice, why can’t the IDA entries in the Curriculum Map translate to M on the Measured Indicators template
o	I was under the impression that only those courses that are being measured will appear on the Curriculum Map. We pulled it up and it listed all courses, which made it difficult to enter data (see first point).
-	It took her about half a day to enter all data on the Measured Indicators template (she was interrupted quite a bit by students, so actual time may have been shorter)
-	Who enters the data for common courses like Eng 4A03? Eng Phys did measure the course but I believe it belongs to Civil Engineering
