### ISSUE TITLE
Measurement Date Field Formatting

### ISSUE THREAD

**Issue by JoeSpan** [smiths/MEASURE#51]
It seems like you have to enter the date as MM-DD-YYYY in order to get DD-MM-YYYY to show up. Otherwise it spits out a "please enter a correct date" error to show up.  I thought that the date function was broken until I tried the backwards approach. It would be nice if at least this were consistent.
@smiths @EvanVena @bhancas 

![image](https://cloud.githubusercontent.com/assets/20819724/18389567/80b0be92-7674-11e6-9ca0-b0c6fb7dce94.png)

**Comment by smiths** [comment]
Hello Joe.  This does seem odd.  Can you comment on this @EvanVena?  I will assign this issue to you.

**Comment by EvanVena** [comment]
Hi @smiths @JoeSpan @bhancas 
the date shows in the formula bar is the default excel date, this can't be change.
under the measurement date, these is a date format to indicate that you should enter the date at "DD-MM-YYYY" format.
 
This is a Microsoft excel function, when you enter a Date format, you have to enter the actual day first, and in the formula bar it will always display the Month first.

Therefore, if you are using excel, and you don't enter the Day first, the value you enter will use as text instead of date.

you can see the example below,
On row#2 - I entered the month first, and use today's date minus the date in B2, excel returns the Error message "#Value"

On row#3 - I entered the day first, and use today's date minus the date in B3, excel returns the actual different between today and the entered date.

PS: there is a way to configure excel to enter month first, but since everybody's computer default at enter day first, it doesn't make sense to do that.

Please let me know, if you have more questions.

![image](https://cloud.githubusercontent.com/assets/20912011/18393662/453ecb0a-7684-11e6-92ac-5516a452ce31.png)

**Comment by JoeSpan** [comment]
@EvanVena I think you have misunderstood the problem. The issue is that when entering the date as (DD-MM-YYYY) in Measure 2.0 an error is triggered. The cell clearly states that the date should be entered as (DD-MM-YYYY) however you must enter it as (MM-DD-YYYY) in order to get the system to "work". 
![image](https://cloud.githubusercontent.com/assets/20819724/18394175/995784dc-7686-11e6-9aaa-ed97a3f2bb99.png)

**Comment by EvanVena** [comment]
Hi Joe,

this doesn't happen to me, when i entered the date 1 "23-08-2016" i didn't
get any error message
when i tried to enter "08-23-2016" warning message pop up.

seems fine to me, can you please try again?

Thanks
Evan

[image: Inline image 1]

**Comment by JoeSpan** [comment]
I tried a different course and still have the same problem. It only will accept the date backwards. What is strange is that it reverses the date after clicking enter. So if you enter the date (MM-DD-YYYY) it will "work" but will show up as (DD-MM-YYYY) 
![image](https://cloud.githubusercontent.com/assets/20819724/18394669/fac12a6e-7688-11e6-857e-3641104dc060.png)

**Comment by EvanVena** [comment]
Hi Joe, can you go to your control panel, and choose "Region and Language"
and do a screenshot for me?
also, the default order of date and month in excel, is linking to the
system.
Thanks
Evan

[image: Inline image 1]

**Comment by EvanVena** [comment]
Hi Joe,
can you also go to your Excel-->Home-->under Number-->go to open up the
excel format windows-->choose date (see the picture below)

This can also be customize as well.

[image: Inline image 1]

**Comment by JoeSpan** [comment]
So in region I was set to English (US), i switched that to English (Canada) 

![image](https://cloud.githubusercontent.com/assets/20819724/18396037/8913b3da-768f-11e6-91b7-bbc8ebfbeb0e.png)

I did the same in excel but it did not fix the problem. @SamGrimshaw , do you have this problem?

**Comment by EvanVena** [comment]
can you close all your excel, then  switch you short date in region to the
following format. then check again
[image: Inline image 1]

**Comment by JoeSpan** [comment]
I am having trouble seeing the image you are trying to show. All I see is [image: Inline image 1]
Can you either describe the format or send me the image to spanjh@mcmaster.ca?
Joe

**Comment by EvanVena** [comment]
here you go
[image: Inline image 1]

Thanks
Evan

**Comment by JoeSpan** [comment]
Yes, now it works. That should be something we put into the instructor guide, possibly in an appendix or troubleshooting section as I doubt I will be the last person to have this problem. 
Thank you @EvanVena

**Comment by smiths** [comment]
I have been following this thread, but I do not know how the problem was resolved.  @JoeSpan , what did you do to fix the issue?  When I test it on my machine, I have the same problem that you originally described.  That is, if I enter the date as DD-MM-YYYY, I get an error message.  I agree that this is a problem that others will have and it will cause unnecessary frustration with MEASURE 2.0.

**Comment by EvanVena** [comment]
Hi @smiths @bhancas @JoeSpan 
This issue is due to the windows setting.
i added the dynamic calculation of today's date in excel based on the windows setting.
So, if your windows is in different region and date format setting,  this can help to reduce the error input.
![image](https://cloud.githubusercontent.com/assets/20912011/18445323/0303619c-78eb-11e6-9d05-745ff55e5aa2.png)

**Comment by smiths** [comment]
Thank you Evan.  This sounds like a reasonable step.  I am able to enter the date now without getting an error message.  I still find it confusing, since 12/09/2016 could mean December 9th or September 12th.  This isn't really a problem with Vena though, this is a consequence of not having a standardized approach to representing dates.

The date is important information, but not critical.  (We always know what term the measurements occur in, even if we don't know the specific date.)

I'm going to close this issue.  @JoeSpan , if you have any remaining concerns, please feel free to reopen the issue.
