### ISSUE TITLE
Two templates for instructor tasks

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#59]
As discussed with @bhancas and @EvanVena , each instructor will be assigned two templates in their tasks: Rubric Input Template and Course Report.  The documentation will have to also be updated to reflect this change.

The motivation for this is so that instructors do not forget to enter the continuous improvement information in the course report.

**Comment by EvanVena** [comment]
Hi @smiths @bhancas 
I combined the two tasks into one. 
So each instructor will have one task, along with some reports.
In order to make structural changes to a started process, i have to restart the process, but nothing change on the data model behind.

please see the below screenshots for more detail.
![image](https://cloud.githubusercontent.com/assets/20912011/18591093/399e7ce8-7bff-11e6-8b96-b294553f756a.png)
![image](https://cloud.githubusercontent.com/assets/20912011/18591109/4b0c7dc2-7bff-11e6-9acd-77307eaa7810.png)

**Comment by smiths** [comment]
This looks good Evan.  Once you restart the process, I would like @SamGrimshaw or @JoeSpan to test it to verify that it is intuitive.

**Comment by JoeSpan** [comment]
Let me know when the process is re-started. I have plenty more reports to enter.

**Comment by EvanVena** [comment]
Hi Joe,

it already did.

Thanks
Evan

**Comment by smiths** [comment]
@JoeSpan is testing the new task where both templates are included.  He should be able to provide feedback soon.

**Comment by smiths** [comment]
I do not recall hearing any feedback on this issue from @JoeSpan, but others have tested the new interface.  The interface seems fine, but the documentation of the interface needs to be clearer.  I will work with @zhengm2 to improve the instructor instructions.
