### ISSUE TITLE
Error Using Excel 2010?

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#82]
When the following Course Report is opened using Excel 2010 the attached error message comes up.  There does not seem to be a problem with Excel 2013.

ENGINEER 1D04, 2013-2014 Term 1, Section 1

[ErrorMessage.pdf](https://github.com/smiths/MEASURE/files/529692/ErrorMessage.pdf)

**Comment by EvanVena** [comment]
@smiths 
this is because the Excel 2010 and Excel 2013 handled default chart type differently, if we changed to matched the excel 2010, then we will likely face the similar issue in excel 2013.

the fix will be changing the default chart type in Excel 2010 to match the bar chart we have.
The Change Chart Type --> Templates --> Select your new template --> Set as default chart

unfortunately i don't have any machine with Excel 2010 installed, please let me know how the test goes.

**Comment by smiths** [comment]
I have been trying to test your fix with Excel 2010, but my VM that has Excel 2010 is not currently working.  I have asked for the VM to be reset, so hopefully I'll be able to test this soon.

**Comment by smiths** [comment]
The Excel 2010 VM is now available to me.  I can reproduce the error message, but I cannot figure out how to use the advice from @EvanVena .  I cannot seem to find a way to access the Chart Type.  The instructions given at the following web-page do not work:

https://support.office.com/en-us/article/Change-the-chart-type-of-an-existing-chart-c686d8c2-b294-43c0-b744-f54000f51454

When I click or right click on any of the charts, no options come up.  I do not see any menu options related to charts.  I have tried both in the Edit Data and Edit Template modes.  There is no difference.  Any ideas?

**Comment by smiths** [comment]
We will close this issue for now.  It will only be relevant if we have an instructor using Excel 2010.
